### ISSUE TITLE
AppCode 配置问题

### ISSUE THREAD

**Issue by CNKCQ** [puretears/MyJetbrainsTheme#1]
我根据您的文章一步一步配置出来，效果如下：
![snip20170709_2](https://user-images.githubusercontent.com/8440220/27987749-71e88f24-6445-11e7-8695-d0997264d3e6.png)
您的演示效果：
![snip20170709_4](https://user-images.githubusercontent.com/8440220/27987760-b3e976d6-6445-11e7-9eff-a8197694d2a5.png)
请问您是如何让顶部共享主题色的？？

**Comment by puretears** [comment]
演示的视频里用的是VS code，JetBrains的IDE现在都不支持自定义标题栏。。

**Comment by CNKCQ** [comment]
哦哦，谢谢！！
